apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevemcghee/go-to-production.git
    targetRevision: main
    path: k8s
    kustomize:
      patches:
        - target:
            kind: Rollout
            name: todo-app-go
          patch: |-
            - op: add
              path: /spec/template/spec/containers/0/env
              value:
                - name: CLUSTER_NAME
                  value: todo-app-cluster
                - name: REGION
                  value: us-central1
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-east
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevemcghee/go-to-production.git
    targetRevision: main
    path: k8s
    kustomize:
      patches:
        - target:
            kind: Rollout
            name: todo-app-go
          patch: |-
            - op: add
              path: /spec/template/spec/containers/0/env
              value:
                - name: CLUSTER_NAME
                  value: todo-app-cluster-secondary
                - name: REGION
                  value: us-east1
  destination:
    name: us-east1
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
