apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: todo-app-go
build:
  artifacts:
  - image: todo-app-go
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: smcghee-todo-p15n-38a6
    region: us-central1
manifests:
  rawYaml:
  - k8s/namespace.yaml
  - k8s/serviceaccount.yaml
  - k8s/deployment.yaml
  - k8s/service.yaml
  - k8s/hpa.yaml
  - k8s/ingress.yaml
  - k8s/managed-certificate.yaml
  - k8s/backend-config.yaml
profiles:
- name: verify
  manifests:
    rawYaml:
    - k8s/verify-job.yaml
- name: backup
  manifests:
    rawYaml:
    - k8s/backup-plan.yaml
