apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: todo-app-go
build:
  artifacts:
  - image: todo-app-go
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: smcghee-todo-p15n-38a6
    region: us-central1
manifests:
  rawYaml:
  - k8s/namespace.yaml
  - k8s/serviceaccount.yaml
  - k8s/deployment.yaml
  - k8s/service.yaml
  - k8s/hpa.yaml
  - k8s/ingress.yaml
  - k8s/managed-certificate.yaml
  - k8s/backend-config.yaml
profiles:
- name: verify
  verify:
      - name: verify-deployment
        container:
          name: verify-healthz
          image: curlimages/curl:latest
          command: ["/bin/sh"]
          args:
          - -c
          - |
            echo "Verifying deployment health..."
            for i in 1 2 3 4 5 6 7 8 9 10; do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://todo-app-go-service:8080/healthz)
              if [ "$STATUS" = "200" ]; then
                echo "Health check passed (attempt $i/5)"
                exit 0
              fi
              echo "Health check failed with status $STATUS (attempt $i/5), retrying..."
              sleep 10
            done
            echo "Health check failed after 5 attempts"
            exit 1
              executionMode: # Removed temporarily for debugging
  manifests:
    rawYaml: []
- name: backup
  manifests:
    rawYaml:
    - k8s/backup-plan.yaml
