apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/refresh: normal
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"todo-app","namespace":"argocd"},"spec":{"destination":{"namespace":"todo-app","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"k8s","repoURL":"https://github.com/stevemcghee/go-to-production.git","targetRevision":"HEAD"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2025-12-19T00:55:15Z"
  generation: 6274
  name: todo-app
  namespace: argocd
  resourceVersion: "1767808227256607020"
  uid: b512780e-48bf-4816-b876-260e37899876
operation:
  sync:
    prune: true
    revision: main
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: todo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/stevemcghee/go-to-production.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Degraded
  history:
  - deployStartedAt: "2025-12-19T03:47:43Z"
    deployedAt: "2025-12-19T03:47:45Z"
    id: 0
    revision: 99b402226523c6e2ba3f903aaaf376e2222e25dc
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T03:52:00Z"
    deployedAt: "2025-12-19T03:52:01Z"
    id: 1
    revision: fb3857df2a2ef9579637d9a98e5cc6d3737db8fb
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T18:33:59Z"
    deployedAt: "2025-12-19T18:34:00Z"
    id: 2
    revision: 82fa070dd83965d7b94e8afb7de03c3f0ae59b84
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T18:35:27Z"
    deployedAt: "2025-12-19T18:35:28Z"
    id: 3
    revision: 7ef042998aae7c81d4d7b87cbc18b988da88085c
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T18:44:17Z"
    deployedAt: "2025-12-19T18:44:20Z"
    id: 4
    revision: b034876e7168d3e95eed746af6f73c7275e9c45f
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T18:44:28Z"
    deployedAt: "2025-12-19T18:44:31Z"
    id: 5
    revision: 9a8a2f46b918e9dffee4dfd1e5abd2b8f13fb3e1
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T18:45:57Z"
    deployedAt: "2025-12-19T18:46:01Z"
    id: 6
    revision: 7530b52bbbff9edc4b97fc006105fa4bd8bbf625
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T18:46:30Z"
    deployedAt: "2025-12-19T18:46:34Z"
    id: 7
    revision: 4593b0783009bdade73d684c81945bbd0771dee2
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T18:57:41Z"
    deployedAt: "2025-12-19T18:57:46Z"
    id: 8
    revision: 830cd1248920ef4fa066547637f5f9376acdcf4c
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  - deployStartedAt: "2025-12-19T22:21:01Z"
    deployedAt: "2025-12-19T22:21:05Z"
    id: 9
    revision: 00b4cc416e1439c561091e10b5fd9ef524d67f88
    source:
      path: k8s
      repoURL: https://github.com/stevemcghee/go-to-production.git
      targetRevision: HEAD
  operationState:
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 00b4cc416e1439c561091e10b5fd9ef524d67f88
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Running
    startedAt: "2026-01-07T17:45:38Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Succeeded
        kind: Namespace
        message: namespace/todo-app unchanged
        name: todo-app
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: templates.gatekeeper.sh
        hookPhase: Succeeded
        kind: ConstraintTemplate
        message: constrainttemplate.templates.gatekeeper.sh/k8srequiredlabels unchanged
        name: k8srequiredlabels
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: templates.gatekeeper.sh
        hookPhase: Succeeded
        kind: ConstraintTemplate
        message: constrainttemplate.templates.gatekeeper.sh/k8sdisallowlatest unchanged
        name: k8sdisallowlatest
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: templates.gatekeeper.sh
        hookPhase: Succeeded
        kind: ConstraintTemplate
        message: constrainttemplate.templates.gatekeeper.sh/k8srequiredresourcelimits
          unchanged
        name: k8srequiredresourcelimits
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: policy
        hookPhase: Running
        kind: PodDisruptionBudget
        message: poddisruptionbudget.policy/todo-app-pdb configured
        name: todo-app-pdb
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/todo-app-sa unchanged
        name: todo-app-sa
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/todo-app-go-service unchanged
        name: todo-app-go-service
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/todo-app-hpa unchanged
        name: todo-app-hpa
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v2
      - group: batch
        hookPhase: Running
        kind: Job
        message: job.batch/create-iam-user unchanged
        name: create-iam-user
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: batch
        hookPhase: Running
        kind: Job
        message: job.batch/db-init unchanged
        name: db-init
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: batch
        hookPhase: Running
        kind: Job
        message: job.batch/verify-job unchanged
        name: verify-job
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: batch
        hookPhase: Running
        kind: CronJob
        message: cronjob.batch/todo-app-load-generator unchanged
        name: todo-app-load-generator
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/todo-app-ingress unchanged
        name: todo-app-ingress
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: constraints.gatekeeper.sh
        hookPhase: Running
        kind: K8sDisallowLatest
        message: k8sdisallowlatest.constraints.gatekeeper.sh/no-latest-tag unchanged
        name: no-latest-tag
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1beta1
      - group: constraints.gatekeeper.sh
        hookPhase: Running
        kind: K8sRequiredLabels
        message: k8srequiredlabels.constraints.gatekeeper.sh/ns-must-have-owner unchanged
        name: ns-must-have-owner
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1beta1
      - group: constraints.gatekeeper.sh
        hookPhase: Running
        kind: K8sRequiredResourceLimits
        message: k8srequiredresourcelimits.constraints.gatekeeper.sh/require-resource-limits
          unchanged
        name: require-resource-limits
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1beta1
      - group: argoproj.io
        hookPhase: Running
        kind: AnalysisTemplate
        message: analysistemplate.argoproj.io/smoke-test unchanged
        name: smoke-test
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      - group: cloud.google.com
        hookPhase: Running
        kind: BackendConfig
        message: backendconfig.cloud.google.com/todo-app-backend-config unchanged
        name: todo-app-backend-config
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.gke.io
        hookPhase: Running
        kind: ManagedCertificate
        message: managedcertificate.networking.gke.io/todo-app-cert unchanged
        name: todo-app-cert
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      - group: argoproj.io
        hookPhase: Running
        kind: Rollout
        message: rollout.argoproj.io/todo-app-go configured
        name: todo-app-go
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      - group: monitoring.googleapis.com
        hookPhase: Running
        kind: PodMonitoring
        message: podmonitoring.monitoring.googleapis.com/todo-app-monitoring unchanged
        name: todo-app-monitoring
        namespace: todo-app
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 00b4cc416e1439c561091e10b5fd9ef524d67f88
      source:
        path: k8s
        repoURL: https://github.com/stevemcghee/go-to-production.git
        targetRevision: HEAD
  reconciledAt: "2025-12-25T12:58:53Z"
  resources:
  - kind: Namespace
    name: todo-app
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: todo-app-go-service
    namespace: todo-app
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: todo-app-sa
    namespace: todo-app
    status: Synced
    version: v1
  - group: argoproj.io
    kind: AnalysisTemplate
    name: smoke-test
    namespace: todo-app
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      message: 'ProgressDeadlineExceeded: ReplicaSet "todo-app-go-6d6f59bdc6" has
        timed out progressing.'
      status: Degraded
    kind: Rollout
    name: todo-app-go
    namespace: todo-app
    status: Synced
    version: v1alpha1
  - group: autoscaling
    health:
      message: recommended size matches current size
      status: Healthy
    kind: HorizontalPodAutoscaler
    name: todo-app-hpa
    namespace: todo-app
    status: Synced
    version: v2
  - group: batch
    kind: CronJob
    name: todo-app-load-generator
    namespace: todo-app
    status: Synced
    version: v1
  - group: batch
    health:
      status: Progressing
    kind: Job
    name: create-iam-user
    namespace: todo-app
    status: Synced
    version: v1
  - group: batch
    health:
      message: Job has reached the specified backoff limit
      status: Degraded
    kind: Job
    name: db-init
    namespace: todo-app
    status: Synced
    version: v1
  - group: batch
    health:
      message: Job has reached the specified backoff limit
      status: Degraded
    kind: Job
    name: verify-job
    namespace: todo-app
    status: Synced
    version: v1
  - group: cloud.google.com
    kind: BackendConfig
    name: todo-app-backend-config
    namespace: todo-app
    status: Synced
    version: v1
  - group: constraints.gatekeeper.sh
    kind: K8sDisallowLatest
    name: no-latest-tag
    status: Synced
    version: v1beta1
  - group: constraints.gatekeeper.sh
    kind: K8sRequiredLabels
    name: ns-must-have-owner
    status: Synced
    version: v1beta1
  - group: constraints.gatekeeper.sh
    kind: K8sRequiredResourceLimits
    name: require-resource-limits
    status: Synced
    version: v1beta1
  - group: monitoring.googleapis.com
    kind: PodMonitoring
    name: todo-app-monitoring
    namespace: todo-app
    status: Synced
    version: v1
  - group: networking.gke.io
    health:
      message: All certificates are active
      status: Healthy
    kind: ManagedCertificate
    name: todo-app-cert
    namespace: todo-app
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: todo-app-ingress
    namespace: todo-app
    status: Synced
    version: v1
  - group: policy
    kind: PodDisruptionBudget
    name: todo-app-pdb
    namespace: todo-app
    status: Synced
    version: v1
  - group: templates.gatekeeper.sh
    kind: ConstraintTemplate
    name: k8sdisallowlatest
    status: Synced
    syncWave: -1
    version: v1
  - group: templates.gatekeeper.sh
    kind: ConstraintTemplate
    name: k8srequiredlabels
    status: Synced
    syncWave: -1
    version: v1
  - group: templates.gatekeeper.sh
    kind: ConstraintTemplate
    name: k8srequiredresourcelimits
    status: Synced
    syncWave: -1
    version: v1
  sourceType: Kustomize
  summary:
    images:
    - curlimages/curl
    - curlimages/curl:latest
    - gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
    - gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    - postgres:15-alpine
    - us-central1-docker.pkg.dev/smcghee-todo-p15n-38a6/todo-app-go/todo-app-go:7ef042998aae7c81d4d7b87cbc18b988da88085c
    - us-central1-docker.pkg.dev/smcghee-todo-p15n-38a6/todo-app-go/todo-app-go:8f50a47f1e1a7d5e1d9d0b3c8e98d093cc695f4b
  sync:
    comparedTo:
      destination:
        namespace: todo-app
        server: https://kubernetes.default.svc
      source:
        path: k8s
        repoURL: https://github.com/stevemcghee/go-to-production.git
        targetRevision: HEAD
    revision: 0c2b50105163329f6b6085fad86a6b338e039086
    status: Synced
